spring:
    application:
        name: Student-management-system
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/std_management
        username: root
    liquibase:
        change-log: classpath*:db/change-log.xml

